### ISSUE TITLE
Build from `rake`

### ISSUE THREAD

**Issue by ylluminate** [opal/opal-browser#22]
We need to implement the ability to build `opal-browser.js` and `opal-browser-canvas.js` by themselves for inclusion in the CDN.  This would be best implemented via a `rake` task it appears.

**Comment by davispuh** [comment]
still no CDN for `opal-browser`?

**Comment by elia** [comment]
v0.2.0 is available for opal v0.8 (see the “Libraries Available” section)

http://cdn.opalrb.org/opal/0.8.0/index.html

**Comment by elia** [comment]
EDIT: didn't see the edit :smile_cat:
