### ISSUE TITLE
Why does Browser::Interval accepts seconds as param?

### ISSUE THREAD

**Issue by KillaPL** [opal/opal-browser#34]
setInterval accepts milliseconds as its parameter, and Browser::Interval accepts seconds. This is very confusing, I just spent quite some time thinking it doesn't work at all, where it simply had very long interval.

Don't you think it should accepts milliseconds as setInterval does?

**Comment by adambeynon** [comment]
Opal-jquery also uses seconds instead of ms. Various ruby libraries, including active support prefer seconds in these cases, so it seems more natural to fit in with fellow ruby libraries rather than the underlying JavaScript which is just an implementation detail.

**Comment by meh** [comment]
What @adambeynon said.

**Comment by KillaPL** [comment]
Okie dokie, thanks for answer.

**Comment by KillaPL** [comment]
Maybe at least a use case example in the readme with comment about the issue would be a good idea?
