### ISSUE TITLE
File input field support

### ISSUE THREAD

**Issue by jgaskins** [opal/opal-browser#35]
I was trying to add file upload support to a Clearwater app (it's using `opal-browser` for DOM interactions now), but I noticed that `Browser::DOM::Element::Input` doesn't support `<input type="file">`. I tried monkeypatching it in so I could submit it as a PR, but wrapping the native JS `FileList` and `File` objects were a bit more than my head was willing to process at the time. Any ideas on how to go about adding this?

**Comment by jgaskins** [comment]
Though probably understandable from context above, I don't think I said it well: what I mean is, for `<input type="file">`, I'd like to add a Ruby accessor for the `files` property.

**Comment by ahmadine** [comment]
I am interested in implementing that
