### ISSUE TITLE
Browser::DOM::NodeSet missing #each method ?

### ISSUE THREAD

**Issue by balmoral** [opal/opal-browser#40]
Browser::DOM::NodeSet calls #each in many places but #each is not implemented.

Also, in `Browser::DOM::Node#<<(node)` the argument is checked to see whether it responds to #each, which if a NodeSet it should but doesn't.

This test code was failing for me at `c << headers`:

```ruby
  def index_ready # in a Volt controller
    c = container
    c << headers
    c.append_to($document.body)
  end

   def container
      DOM {
        div(class: 'container', id: 'container1')
      }
    end

    def headers
      DOM {
        div.h1.style(color: 'blue') {
          "Heading 1"
        }
        div.h2.style(color: 'red')  {
          "Heading2"
        }
      }
    end
 ```

The following patch to NodeSet fixed the problem:

```ruby
class NodeSet
  ...
  def each(&block)
    @literal.each do |e|
      yield e
    end
end
```

**Comment by meh** [comment]
`NodeSet#each` comes from `NodeSet#method_missing`, the actual bug was that `NodeSet#respond_to_missing?` wasn't implemented.

It's now implemented on master, so it should work, reopen the issue if it's not the case.

**Comment by balmoral** [comment]
Works now. Thanks for fast fix.

**Comment by meh** [comment]
You were lucky, I just got out of bed because I couldn't sleep :panda_face:

**Comment by balmoral** [comment]
You've built some pretty amazing tools here. Do hope you get some well-deserved rest. :smile:
