### ISSUE TITLE
A file required wasn't found

### ISSUE THREAD

**Issue by bigtunacan** [opal/opal-browser#41]
I was trying to generate the js file so I can include into my HTML as follows

    opal --compile lib/opal-browser.rb > opal-browser.js

It is erring out with the following

    A file required by "lib/opal-browser.rb" wasn't found. (Opal::Builder::MissingRequire)
    
    can't find file: "opal/browser" in [
      "/Users/meh/.rvm/gems/ruby-1.9.3-p547@ob/gems/opal-0.8.0/opal",
      "/Users/meh/.rvm/gems/ruby-1.9.3-p547@ob/gems/opal-0.8.0/stdlib",
      "/Users/meh/.rvm/gems/ruby-1.9.3-p547@ob/gems/opal-0.8.0/lib"
    ]

**Comment by meh** [comment]
`lib/opal-browser` is for the MRI side of things, what you're looking for is in `opal/`.

**Comment by bigtunacan** [comment]
@meh 

Not sure what I'm doing, but still getting a similar error.

Tried both of the following with similar results.

    opal --compile opal/browser.rb > browser.js
    opal --compile opal/opal-browser.rb > browser.js

    /Users/meh/.rvm/gems/ruby-1.9.3-p547@ob/gems/opal-0.8.0/lib/opal/builder.rb:118:in `read': A file     required by "opal/browser.rb" wasn't found. (Opal::Builder::MissingRequire)
      can't find file: "paggio" in [
        "/Users/meh/.rvm/gems/ruby-1.9.3-p547@ob/gems/opal-0.8.0/opal",
        "/Users/meh/.rvm/gems/ruby-1.9.3-p547@ob/gems/opal-0.8.0/stdlib",
        "/Users/meh/.rvm/gems/ruby-1.9.3-$547@ob/gems/opal-0.8.0/lib"
      ]

**Comment by meh** [comment]
`opal --gem paggio --compile opal/browser.rb > browser.js`

**Comment by bigtunacan** [comment]
opal --gem paggio --compile opal/browser.rb > browser.js

    /Users/meh/.rvm/gems/ruby-1.9.3-p547@ob/gems/opal-0.8.0/lib/opal/builder.rb:118:in `read': A file required by "opal/browser.rb" wasn't found. (Opal::Builder::MissingRequire)
      can't find file: "browser/version" in [
        "/Users/meh/.rvm/gems/ruby-1.9.3-p547@ob/gems/opal-0.8.0/opal",
        "/Users/meh/.rvm/gems/ruby-1.9.3-p547@ob/gems/opal-0.8.0/stdlib",
        "/Users/meh/.rvm/gems/ruby-1.9.3-p547@ob/gems/opal-0.8.0/lib",
        "/Users/meh/.rvm/gems/ruby-1.9.3-p547@ob/bundler/gems/paggio-59ac18e4dfb3/lib"
       ]
