### ISSUE TITLE
Browser::Storage won't work

### ISSUE THREAD

**Issue by fazibear** [opal/opal-browser#48]
Whem I write something to local storage and save it, after refresh I'll get this errors:

Opal 0.8:

```
Uncaught TypeError: Opal.cget is not a function
```

Opal 0.9

```
Uncaught NameError: uninitialized constant Object::Browser::Storage
```

**Comment by meh** [comment]
Did you try to use master for both opal-browser and opal?

**Comment by fazibear** [comment]
For both gems with master everything works fine. Thanks.
