### ISSUE TITLE
Compile Error: browser/database/sql.rb -- Line 76

### ISSUE THREAD

**Issue by mistergibson** [opal/opal-browser#69]
while compiling opal-browser, got the following error:

browser/database/sql:76:54: error: unexpected token tRCURLY
browser/database/sql:76:       #{-> t { block.call(Transaction.new(self, t)) }})`
browser/database/sql:76:                                                      ^  
/var/lib/gems/2.4.0/gems/parser-2.3.3.1/lib/parser/diagnostic/engine.rb:71:in `process': unexpected token tRCURLY (SyntaxError)
	from /var/lib/gems/2.4.0/gems/parser-2.3.3.1/lib/parser/base.rb:263:in `on_error'
	from /usr/lib/ruby/2.4.0/racc/parser.rb:259:in `_racc_do_parse_c'
	from /usr/lib/ruby/2.4.0/racc/parser.rb:259:in `do_parse'
	from /var/lib/gems/2.4.0/gems/parser-2.3.3.1/lib/parser/base.rb:162:in `parse'
	from /var/lib/gems/2.4.0/gems/opal-0.11.0/lib/opal/parser.rb:41:in `parse'
	from /var/lib/gems/2.4.0/gems/parser-2.3.3.1/lib/parser/base.rb:209:in `tokenize'
	from /var/lib/gems/2.4.0/gems/opal-0.11.0/lib/opal/compiler.rb:180:in `parse'
	from /var/lib/gems/2.4.0/gems/opal-0.11.0/lib/opal/compiler.rb:166:in `compile'
	from /var/lib/gems/2.4.0/gems/opal-0.11.0/lib/opal/builder_processors.rb:88:in `compiled'
	from /var/lib/gems/2.4.0/gems/opal-0.11.0/lib/opal/builder_processors.rb:98:in `requires'
	from /var/lib/gems/2.4.0/gems/opal-0.11.0/lib/opal/builder.rb:199:in `process_require'
	from /var/lib/gems/2.4.0/gems/opal-0.11.0/lib/opal/builder.rb:88:in `block in build_str'
	from /var/lib/gems/2.4.0/gems/opal-0.11.0/lib/opal/builder.rb:88:in `map'
	from /var/lib/gems/2.4.0/gems/opal-0.11.0/lib/opal/builder.rb:88:in `build_str'
	from /var/lib/gems/2.4.0/gems/opal-0.11.0/lib/opal/cli.rb:109:in `block in create_builder'
	from /var/lib/gems/2.4.0/gems/opal-0.11.0/lib/opal/cli.rb:149:in `evals_or_file'
	from /var/lib/gems/2.4.0/gems/opal-0.11.0/lib/opal/cli.rb:109:in `create_builder'
	from /var/lib/gems/2.4.0/gems/opal-0.11.0/lib/opal/cli.rb:84:in `builder'
	from /var/lib/gems/2.4.0/gems/opal-0.11.0/lib/opal/cli.rb:62:in `run'
	from /var/lib/gems/2.4.0/gems/opal-0.11.0/exe/opal:24:in `<top (required)>'
	from /usr/local/bin/opal:23:in `load'
	from /usr/local/bin/opal:23:in `<main>'

**Comment by iliabylich** [comment]
Thanks!
Fixed in https://github.com/opal/opal-browser/commit/b14a4dcf4f68c87c5bb1b108839560d34c77d6af
