### ISSUE TITLE
basic install and test - RubyMine2018 ubuntu14.04

### ISSUE THREAD

**Issue by ozpos** [opal/opal-browser#75]
Hi all, Thank you for opal, no one likes js when there is ruby.

I am hitting a few problems with gem versions that create depreciation warnings. (DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.)

Could anyone please tell me what ruby version I should be building under ?
Best regards,ozpos

**Comment by ahmadine** [comment]
The latest and greatest opal-browser requires at least Opal 1.0.0. I think the earliest version of Ruby that's supported by Opal 1.0.0 is 2.3, but the best supported ones are 2.5 and 2.6. As far as I know, this deprecation warning doesn't happen anymore.

I'm closing this issue in a process of tidying up issues of this project. Please feel free to reopen it if it is still relevant :)
