### ISSUE TITLE
require 'browser/setup/full' not work.

### ISSUE THREAD

**Issue by zw963** [opal/opal-browser#90]
#<Sprockets::FileNotFound: couldn't find file 'browser/setup/full' with type 'application/javascript'

```sh
 ╰─ $ bundle list |grep opal
  * opal (1.2.0)
  * opal-browser (0.2.0)
  * opal-sprockets (1.0.1)
```

**Comment by zw963** [comment]
Wired, this issue only happen when i install opal-browser use gem command, if use github repo master, no issue.

**Comment by zw963** [comment]
maybe we should release this gem first, and then close this issue?

**Comment by hmdne** [comment]
We are working on the release; ref meh/paggio#7

**Comment by zw963** [comment]
though i start to use Opal recent days, but, i pay close attention to this project several years, don't know why @meh not so active for now, i remember he is a main opal early submitter.

I do have a advice, we can merge (part of) paggio gem code into opal-browser directly instead get owner of that gem, if we keep dragging to wait that gem maintainer, it very bad to Opal community.

**Comment by zw963** [comment]
In fact, i consider generate HTML and CSS use ruby. should be part of opal-browser, what do you think? @hmdne

**Comment by hmdne** [comment]
@zw963
1. paggio should stay separate because it can be used without Opal (ie. as a template engine)
2. paggio itself is quite heavy and isn't needed by Opal-Browser (browser/setup/full requires it but eg. browser/setup/large doesn't)
3. I don't know about meh (I joined the project long after he became inactive), he seems mostly invested in the Rust ecosystem nowadays. We need to be patient about all this, because we also can't release opal-browser at the current time

**Comment by hmdne** [comment]
We can now push releases! Let this issue stay open until we do :D

**Comment by zw963** [comment]
> We can now push releases! Let this issue stay open until we do :D

so, we rename paggio to `opal-web`, right?

**Comment by hmdne** [comment]
> > We can now push releases! Let this issue stay open until we do :D
> 
> so, we rename paggio to `opal-web`, right?

No. I proposed renaming `opal-browser` to `opal-web`, because `opal-browser` shared the same problem with `paggio` (no permissions to release a Gem).

But fortunately, we have been transferred rights to both `opal-browser` and `paggio` so we can finally do a release.

**Comment by zw963** [comment]
When to release opal-browser ? anyway, fetch gem from github is slow.

**Comment by hmdne** [comment]
I shall be ready to do a release in a few days

**Comment by hmdne** [comment]
Opal-Browser v0.3.0 along with Paggio v0.3.0 are released now!
