### ISSUE TITLE
Should we require "browser/http.rb" into "browser/setup/traditional.rb" ?

### ISSUE THREAD

**Issue by zw963** [opal/opal-browser#94]
Just curious, why `browser/http.rb` not belongs to traditional.

Thank you.

**Comment by hmdne** [comment]
It's a traditional set of requires for those who `require 'browser'` and not adjust their dependencies, basically a legacy thing we may get rid of someday when we decide to break compatibility. See #60

**Comment by zw963** [comment]
Thank you!
